INSERT INTO Clientes (id, nombre, apellidos, email, creado) VALUES (1, 'Jesús', 'Sánchez Bertolín', 'jsbertolin@gmail.com', '2018-03-07');
INSERT INTO Clientes (id, nombre, apellidos, email, creado) VALUES (2, 'Jero', 'Gutiérrez Martín', 'cgmart@gmail.com', '2018-04-20');
INSERT INTO Clientes (id, nombre, apellidos, email, creado) VALUES (3, 'Marcos', 'González García', 'mgarcia@gmail.com', '2019-07-23');
INSERT INTO Clientes (id, nombre, apellidos, email, creado) VALUES (4, 'Marta', 'Sánchez Iglesias', 'marts@gmail.com', '2019-07-23');
INSERT INTO Clientes (id, nombre, apellidos, email, creado) VALUES (5, 'Pablo', 'Casado Rivera', 'pcr@gmail.com', '2019-05-26');
INSERT INTO Clientes (id, nombre, apellidos, email, creado) VALUES (6, 'Pau', 'Sánchez García', 'pausa@gmail.com', '2019-04-22');
INSERT INTO Clientes (id, nombre, apellidos, email, creado) VALUES (7, 'Sergio', 'Bertolín Martínez', 'seberm@gmail.com', '2019-02-21');
INSERT INTO Clientes (id, nombre, apellidos, email, creado) VALUES (8, 'Santiago', 'Pérez Romero', 'sperez@gmail.com', '2017-02-26');
INSERT INTO Clientes (id, nombre, apellidos, email, creado) VALUES (9, 'Rosa', 'Costa Sánchez', 'rcosta@gmail.com', '2018-12-23');